config/routes.rb
Rails.application.routes.draw do
  resources :products
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :tests, except: [:index]
  resources :reports, except: [:index]
  resources :inspections, except: [:index]
  resources :systems, except: [:index]
  resources :accounts
  resources :reps
  post '/reps/:id/reassign', to: 'reps#reassign', as: 'reassign_rep'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rep.rb
class Rep < ApplicationRecord
  has_many :accounts
  has_many :reports
  has_secure_password


  def sort_account_inspections
    sorted_hash = {}
     self.accounts.each do |account|
        sorted_hash[account] = account.inspections.sort_by &:inspection_date
    end
    sorted_hash
  end

  def reassign_rep(new_rep_id)
    self.accounts.each do |account|
      account.update(rep_id: new_rep_id)
    end
    self.reports.each do |report|
      report.update(rep_id: new_rep_id)
    end
  end

end #end of rep model

app/controllers/reps_controller.rb
class RepsController < ApplicationController
  before_action :find_rep, only: [:show, :edit, :update, :destroy]
  # validates :username, uniqueness: true

  def index
      if Rep.where('name LIKE ?', "%#{params[:search]}%").length > 0
        @reps  = Rep.where('name LIKE ?', "%#{params[:search]}%")
      else
        @reps = Rep.all
      #implicit index render
      end
    end

    def show
    end

    def new
      @rep = Rep.new
      #implicit new render
    end

    def create
      @rep = Rep.create(rep_params)
      if @rep.valid?
        session[:rep_id] = @rep.id
        redirect_to @rep
      else
        @errors = @rep.errors.full_messages
        render :new
      end
    end

    def edit
      #implicit edit render
    end

    def update
      # @new_rep = params["rep"["id"]]
      # @new_rep.to_i
      # byebug
      if @rep.update(rep_params)
        redirect_to @rep
      else
        @errors = @rep.errors.full_messages
        render :edit
      end
    end

    def reassign
      new_rep_id = params[:id]
      reassign_rep(new_rep_id)
    end

    def destroy
      @rep.destroy
      redirect_to reps_path
      flash[:notice] = "You deleted your account."
    end

  private
    ###private methods
    def rep_params
      params.require(:rep).permit(:name, :region, :username, :password, :rep, :id, :search)
    end

    def find_rep
      @rep = Rep.find(params[:id])
    end


end ##end of reps controller class

app/helpers/reps_helper.rb
module RepsHelper
end

app/views/reps/edit.erb
<div class="row">
  <div class="col-md" align="center">
    <h1>Edit <%= @rep.name %></h1>
    <div><% if @errors   %>
    <ul><% @errors.each do |error| %>
    <li><%= error %></li>
    <% end %>
    </ul>
    <% end %>
    </div>
    <%= form_for @rep do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br><br>
    <%= f.label :region %><br>
    <%= f.text_field :region %><br><br>
    <%= f.label :username%><br>
    <%= f.text_field :username%><br><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br><br>
    <%= f.submit(class: "button")%>
    <% end %>
  </div>
  <div class="col-md" align="left">
    <h2>Edit/delete <%= @rep.name %> accounts</h2>
        <% @rep.accounts.each do |account| %>
        <label ><%= account.name %></label><br>
        <div class="btn-group">
        <%= button_to "Edit", edit_account_path(account), method: "get", class: "button" %>
        <%= button_to "Delete", account_path(account), method: "delete", class: "button" %>
      </div>
      <% end %>
      <h3>Add accounts to <%= @rep.name %></h3>
      <%= button_to "New Account", new_account_path, method: "get", class: "button" %>
  </div>



</div>

app/views/reps/index.erb
<div class="jumbotron" style="max-width:50%;margin-left:25%">
<h3 align="center">Search For a Rep by Name: </h3>

<div align="center">
<%= form_tag(reps_path, method: :get) do %>
  Name: <%= text_field_tag :search, params[:search] %>
  <%= submit_tag 'Search', name: nil, class: "button" %>
<% end %> <br>
<% if @reps.length != Rep.all.length %>
<%= button_to "Back", reps_path, method: "get", class: "button" %>
<% end %>
<br>


<h1>Here are all of your Reps!</h1>
<% @reps.each do |rep| %>
<span><%= link_to rep.name, rep_path(rep)%></span><br>
<% end %>

</div>
</div>

app/views/reps/new.erb
<div class="jumbotron" style="max-width:50%;margin-left:25%">
<h1 align="center"> Add a new rep </h1>
<div align="center">
  <%= form_for @rep do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br>
  <%= f.label :region %><br>
  <%= f.text_field :region %><br><br>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br><br>
  <%= f.label :password %><br>
  <%= f.text_field :password %><br><br>
  <%= f.submit(class: "button") %>
  <% end %>
</div>
</div>

app/views/reps/show.erb
<div class="container">
    <h1><%= @rep.name %></h1>
    <h3>Region: <%= @rep.region %></h3>
    <table>
      <tr>
        <td><%= button_to "Edit", edit_rep_path(@rep), method: "get", class: "button" %></td>
        <td><%= button_to "BACK", reps_path, method: "get", class: "button" %></td>
      </tr>
    </table>
</div><br><br>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h1>ACCOUNTS</h1>
      <% @rep.accounts.each do |account| %>
      <p><%= account.name %>, <%= account.acct_num %></p>
      <table>
        <tr>
          <td><%= button_to "Account Info", account_path(account), method: "get", class: "button" %></td>
          <td><%= button_to "Edit", edit_account_path(account), method: "get", class: "button" %></td>
          <td><%= button_to "Delete", account_path(account), method: "delete", class: "button" %></td>
        </tr>
      </table><br>
      <% end %>
    </div>
    <div class="col-md-4">
      <h1 align="center">INSPECTIONS</h1>
      <span align="center"> <%= button_to "ADD NEW INSPECTION", new_inspection_path, method: "get", class: "button" %></span><br>
      <%@rep.accounts.each  do |account| %>
      <div align="center">
        <h3><%= account.name %></h3>
          <%account.inspections.each do |inspection|%>
          <span align="center">Report Date: <%= link_to "#{inspection.inspection_date.strftime("%^B %m %Y")}", inspection_path(inspection) %></span><br>
          <% end %><br>
      </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <h1 align="center">REPORTS</h1>
      <% @rep.reports.each do |report| %>
      <span align="center"><%=link_to "#{report.system.system_type}:  #{report.created_at.strftime("%^B %m %Y")}", report_path(report)%><br></span>
      <% end %>
    </div>
  </div>
</div>