config/routes.rb
Rails.application.routes.draw do
  resources :products
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :tests, except: [:index]
  resources :reports, except: [:index]
  resources :inspections, except: [:index]
  resources :systems, except: [:index]
  resources :accounts
  resources :reps
  post '/reps/:id/reassign', to: 'reps#reassign', as: 'reassign_rep'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :test
  belongs_to :system
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def new
    @product = Product.new
    #implicit new render
  end

  def show
  end
  def create
    @product = Product.create(product_params)
    if @product.valid?
      redirect_to @product
    else
      @errors = @product.errors.full_messages
      render :edit
    end
  end
  private
  ###private methods
  def product_params
    params.require(:product).permit(:name, :test_id, :system_id, :search)
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.erb
<div class="jumbotron" style="max-width:40%;margin-left:30%">

<h1 align="center"> EDIT <%= @test.name %> TEST</h1><br>
<div><% if @errors   %>
<ul><% @errors.each do |error| %>
<li><%= error %></li>
<% end %>
</ul>
<% end %>
</div>
<div>
<table align="center">
<tr>
  <td>
  <%= form_for @test do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br>
  <%= f.label :reading %><br>
  <%= f.number_field :reading %><br><br>
  <%= f.label :comment %><br>
  <%= f.text_area :comment %><br>
  </td>
</tr>
<tr>

  <td align="center">
  <div class="btn-group"><%= f.submit(class: "button") %>
  <% end %>
  <%= button_to "Delete", test_path(@test), method: "delete", class: "button" %>
  </div>
  </td>
</tr>
</table>
</div>

app/views/products/index.erb
<div class="jumbotron" style="max-width:40%;margin-left:30%">

  <h3 align="center">Search For a Test: </h3>

  <%= form_tag(tests_path, method: :get) do %>
    Name: <%= text_field_tag :search, params[:search] %>
    <%= submit_tag 'Search', name: nil, class: "button" %>
  <% end %> <br>
  <% if @tests.length != Test.all.length %>
  <%= button_to "Back", tests_path, method: "get", class: "button" %>
  <% end %>
  <br>


  <h1>Here are All of the tests for Barclay</h1>
  <% @tests.each do |test| %>
  <span><%= link_to test.name, test_path(test)%></span><br>
  <% end %>
</div>

app/views/products/new.erb
  <div class="jumbotron" style="max-width:40%;margin-left:30%">

  <h1 align="center"> Add a new Test </h1><br>
  <div><% if @errors   %>
  <ul><% @errors.each do |error| %>
  <li><%= error %></li>
  <% end %>
  </ul>
  <% end %>
  </div>
  <div>
<table align="center">
  <tr>
    <td>  <%= form_for @product do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name %><br><br>
      <%= f.label :system_id %><br>
      <%= f.number_field :system_id %><br><br>
      <%= f.label :test_name %><br>
      <% Test.all.each do |test| %>
      <select name="test_id">
        <%= test.id %>
      </select>
      <% end %>
      <br><br>
    </td>
  </tr>
  <tr>
    <td align="center">  <%= f.submit(class: "button") %></td>
  </tr>
</table>


  <% end %>
  </div>
  </div>

app/views/products/show.erb
<div class="jumbotron" style="max-width:40%;margin-left:30%">
    <h1 align="center">TEST</h1>
    <table align="center">
      <tr>
        <th align="center" style="padding-right:20px">TEST NAME: </th>
        <td align="center"><%= @test.name %></td>
      </tr>
      <tr>
        <th align="center" style="padding-right:20px">READING: </th>
        <td align="center"><%= @test.comment %></td>
      </tr>
    </table>
<br>
    <span align="center"><%= button_to "EDIT TEST", edit_test_path(@test), method: "get", class: "button"%></span>
    </div>