config/routes.rb
Rails.application.routes.draw do
  resources :products
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :tests, except: [:index]
  resources :reports, except: [:index]
  resources :inspections, except: [:index]
  resources :systems, except: [:index]
  resources :accounts
  resources :reps
  post '/reps/:id/reassign', to: 'reps#reassign', as: 'reassign_rep'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :rep
  has_many :systems
  has_many :inspections

  def last_inspection
    if self.inspections.length == 0
      sorted = [Inspection.new()]
    else
    sorted = self.inspections.sort_by &:inspection_date
  end
    sorted.last
  end

##this == last_inspection but not ideal. Can use this to sort a new inspection date column)
  def last_inspection_two
    sorted = self.inspections.sort{|a,b| a.created_at <=> b.created_at}
    sorted.last
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inspection.rb
class Inspection < ApplicationRecord
  belongs_to :system
  belongs_to :account

  def inspection_choices
    choices = {"Good Condition" => 1, "Some Noticable Aging" => 2, "Action Needed" => 3}
  end

  def insp_track_helper
    date = self.inspection_date + 90.days
    date.strftime("%^B %d, %Y")
  end

  def inspection_track
    if self.id == nil
      "There are no inspections available for this account."
    else
      if self.inspection_date + 90.days < Time.now
      "You are past your inspection due date, it was due #{insp_track_helper}!"
      else
      "Your next inspection should be on: \n #{insp_track_helper}."
      end
    end
  end

  def self.systems_uniq
    systems_array = System.all.uniq
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :test
  belongs_to :system
end

app/models/rep.rb
class Rep < ApplicationRecord
  has_many :accounts
  has_many :reports
  has_secure_password


  def sort_account_inspections
    sorted_hash = {}
     self.accounts.each do |account|
        sorted_hash[account] = account.inspections.sort_by &:inspection_date
    end
    sorted_hash
  end

  def reassign_rep(new_rep_id)
    self.accounts.each do |account|
      account.update(rep_id: new_rep_id)
    end
    self.reports.each do |report|
      report.update(rep_id: new_rep_id)
    end
  end

end #end of rep model

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :system
  belongs_to :rep

end

app/models/system.rb
class System < ApplicationRecord
  belongs_to :account
  has_many :inspections
  has_many :reports
  has_many :products
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :products
end #end of test class

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :find_report, only: [:show, :edit, :update]

    def show
    end

    def new
      if params[:system]
        @account = Account.find(params[:system][:account_id])
        @report = Report.new(rep_id: current_rep.id)
        render :new
      else
        @report = Report.new(rep_id: current_rep.id)
        render :new
      end
    end

    def create
      @report = Report.create(report_params)
      if @report.valid?
        @test = Test.all.find(1)
        @test2 = Test.all.find(2)
        render :new_report
      else
        @errors = @report.errors.full_messages
        render :new
      end
    end

    def edit
      #before-action gives instance
      #implicit edit render
    end

    def update
      if @report.update(report_params)
        redirect_to @report
      else
        @errors = @report.errors.full_messages
        render :edit
      end
    end

    #No destroy, this could delete the rep and accounts as dependencies maybe?
    # def destroy
    #   @report.destroy
    #   redirect_to reports_path
    # end

  private
    ###private methods
    def report_params
      params.require(:report).permit(:rep_id, :system_id)
    end

    def find_report
      @report = Report.find(params[:id])
    end


end #end of reports controller class

app/controllers/reps_controller.rb
class RepsController < ApplicationController
  before_action :find_rep, only: [:show, :edit, :update, :destroy]
  # validates :username, uniqueness: true

  def index
      if Rep.where('name LIKE ?', "%#{params[:search]}%").length > 0
        @reps  = Rep.where('name LIKE ?', "%#{params[:search]}%")
      else
        @reps = Rep.all
      #implicit index render
      end
    end

    def show
    end

    def new
      @rep = Rep.new
      #implicit new render
    end

    def create
      @rep = Rep.create(rep_params)
      if @rep.valid?
        session[:rep_id] = @rep.id
        redirect_to @rep
      else
        @errors = @rep.errors.full_messages
        render :new
      end
    end

    def edit
      #implicit edit render
    end

    def update
      # @new_rep = params["rep"["id"]]
      # @new_rep.to_i
      # byebug
      if @rep.update(rep_params)
        redirect_to @rep
      else
        @errors = @rep.errors.full_messages
        render :edit
      end
    end

    def reassign
      new_rep_id = params[:id]
      reassign_rep(new_rep_id)
    end

    def destroy
      @rep.destroy
      redirect_to reps_path
      flash[:notice] = "You deleted your account."
    end

  private
    ###private methods
    def rep_params
      params.require(:rep).permit(:name, :region, :username, :password, :rep, :id, :search)
    end

    def find_rep
      @rep = Rep.find(params[:id])
    end


end ##end of reps controller class

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, only: [:show, :edit, :update, :destroy]


  def index
    if Test.where('name LIKE ?', "%#{params[:search]}%").length > 0
      @tests  = Test.where('name LIKE ?', "%#{params[:search]}%")
    else
      @tests = Test.all
    #implicit index render
    end
  end

  def new
    @test = Test.new
    #implicit new render
  end
  def show
  end
  def create
    @test = Test.create(test_params)
    if @test.valid?
      redirect_to @test
    else
      @errors = @test.errors.full_messages
      render :edit
    end
  end

  def edit
    #implicit edit render
  end

  def update
    if @test.update(test_params)
      redirect_to @test
    else
      @errors = @test.errors.full_messages
      render :edit
    end
  end

  def destroy
    @test.destroy
    redirect_to tests_path
  end


  private
  ###private methods
  def test_params
    params.require(:test).permit(:name, :reading, :comment, :report_id, :search)
  end

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reps_helper.rb
module RepsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barclay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="application.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/solid.css" integrity="sha384-+0VIRx+yz1WBcCTXBkVQYIBVNEFH1eP6Zknm16roZCyeNg2maWEpk/l/KsyFKs7G" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/regular.css" integrity="sha384-aubIA90W7NxJ+Ly4QHAqo1JBSwQ0jejV75iHhj59KRwVjLVHjuhS3LkDAoa/ltO4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/brands.css" integrity="sha384-1KLgFVb/gHrlDGLFPgMbeedi6tQBLcWvyNUN+YKXbD7ZFbjX6BLpMDf0PJ32XJfX" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/fontawesome.css" integrity="sha384-jLuaxTTBR42U2qJ/pm4JRouHkEDHkVqH0T1nyQXn1mZ7Snycpf6Rl25VBNthU4z0" crossorigin="anonymous">
  </head>

  <body>
    <header>
      <div class="topnav">
        <%= link_to "Barclay Water", login_path%>
        <%=link_to "Accounts", accounts_path%>
        <%= link_to "New Account", new_account_path%>
        <%=link_to "New Report", new_report_path%>
        <%=link_to "New Inspection", new_inspection_path%>
        <%=link_to "Reps", reps_path%>
        <%= link_to "New Rep", new_rep_path%>
      <div class="login-container">
          <%= link_to "Log Out", logout_path, :method => :delete %>
      </div>
    </div>
    </header>

    <div class="containerr">
      <%= yield %>
    </div>
    <footer>
      <h6>Created by JoshSea 2019</h6>
      <h6>ruby on rails, SQLite3, bootstrap</h6>
      <h6><a href="https://github.com/josh-sea" target="_blank">GitHub</a></h6>

    </footer>
  </body>
</html>