config/routes.rb
Rails.application.routes.draw do
  resources :products
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :tests, except: [:index]
  resources :reports, except: [:index]
  resources :inspections, except: [:index]
  resources :systems, except: [:index]
  resources :accounts
  resources :reps
  post '/reps/:id/reassign', to: 'reps#reassign', as: 'reassign_rep'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :rep
  has_many :systems
  has_many :inspections

  def last_inspection
    if self.inspections.length == 0
      sorted = [Inspection.new()]
    else
    sorted = self.inspections.sort_by &:inspection_date
  end
    sorted.last
  end

##this == last_inspection but not ideal. Can use this to sort a new inspection date column)
  def last_inspection_two
    sorted = self.inspections.sort{|a,b| a.created_at <=> b.created_at}
    sorted.last
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
before_action :find_account, only: [:show, :edit, :update, :destroy]

  def index
      if current_rep.accounts.where('name LIKE ?', "%#{params[:search]}%").length > 0
        @accounts  = current_rep.accounts.where('name LIKE ?', "%#{params[:search]}%")
      else
        @accounts = current_rep.accounts
      #implicit index render
      end
    end

    def new
      @account = Account.new
      #implicit new render
    end
    def show
    end
    def create
      @account = Account.create(account_params)
      if @account.valid?
        redirect_to @account
      else
        @errors = @account.errors.full_messages
        render :edit
      end
    end

    def edit
      #implicit edit render
    end

    def update
      if @account.update(account_params)
        redirect_to @account
      else
        @errors = @account.errors.full_messages
        render :edit
      end
    end

    def destroy
      @account.destroy
      redirect_to accounts_path
    end


  private
    ###private methods
    def account_params
      params.require(:account).permit(:name, :acct_num, :rep_id, :search)
    end

    def find_account
      @account = Account.find(params[:id])
    end

    def require_login
      return head(:forbidden) unless session.include? :username
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.erb
  <div class="jumbotron" style="max-width:50%;margin-left:25%">
    <h1 align="center">Edit <%= @account.name %></h1>
    <div align="center">
    <div><% if @errors   %>
    <ul><% @errors.each do |error| %>
    <li><%= error %></li>
    <% end %>
    </ul>
    <% end %>
    </div>

    <%= form_for @account do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :acct_num %>
    <%= f.number_field :acct_num %><br><br>
    <%= collection_select(:account, :rep_id, Rep.all, :id, :name)%>
    <div class="btn-group">
    <%= f.submit(class: "button") %>
    <% end %>
    <%= button_to "Delete", account_path(@account), method: "delete", class: "button" %>
  </div>
  </div>
  </div>

app/views/accounts/index.erb
<div class="jumbotron" style="max-width:50%;margin-left:25%">
  <h3 align="center">Search For an Account by Name: </h3>
  <div align="center">
    <table>
      <tr>
        <td><%= form_tag(accounts_path, method: :get) do %>
          Name: <%= text_field_tag :search, params[:search] %>
          <%= submit_tag 'Search', name: nil, class: "button" %>
          <% end %>
        </td>
        <td><% if @accounts.length != current_rep.accounts.length %>
              <%= button_to "Back", accounts_path, method: "get", class: "button" %>
            <% end %>
        </td>
      </tr>
    </table>
      <br>
      <hr>

      <h1><%= current_rep.name.upcase %> ACCOUNTS</h1>
      <% @accounts.each do |account| %>
      <span><%= link_to account.name, account_path(account)%></span><br>
      <% end %>
</div>
  </div>

app/views/accounts/new.erb
  <div class="jumbotron">
    <h1> Add a new Account </h1>
    <div><% if @errors   %>
    <ul><% @errors.each do |error| %>
    <li><%= error %></li>
    <% end %>
    </ul>
    <% end %>
    </div>
    <%= form_for @account do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :acct_num %>
    <%= f.number_field :acct_num %>
    <%= f.label :rep_id %>
    <%= collection_select(:account, :rep_id, Rep.all, :id, :name) %>
    <%= f.submit(class: "button") %>
    <% end %>
  </div>

app/views/accounts/show.erb
  <div class="jumbotron">
    <div class="col-md-4">
      <span align="center">
      <h1 align="center">ACCOUNT INFO</h1>
      <p>ACCOUNT NAME: <%= @account.name %></p>
      <p>ACCOUNT NUMBER: <%= @account.acct_num %></p>
      <p>REP NAME: <%= @account.rep.name %></p>
      </span>
      <table align="center">
        <tr>
          <td>
            <div class="btn-group">
              <span align="center"><%= button_to "EDIT ACCOUNT", edit_account_path(@account), method: "get", class: "button"%></span>
              <span align="center"><%= button_to "EDIT REP INFO", edit_rep_path(@account.rep), method: "get", class: "button" %></span>
              <span align="center"><%= button_to "VIEW REP", rep_path(@account.rep), method: "get", class: "button" %></span>
            </div>
          </td>
        </tr>
      </table>
    </div>

  <br><br>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h1 align="center">SYSTEMS</h1>
        <% @account.systems.each do |system| %>
        <p>SYSTEM NAME: <%= system.system_type %></p>
        <p>SYSTEM TREATMENT: <%= system.treatment_comment %></p>
        <div class="btn-group">
          <span align="center"><%= button_to "EDIT SYSTEM", edit_system_path(system), method: "get", class: "button" %></span>
          <span align="center"><%= button_to "VIEW SYSTEM", system_path(system), method: "get", class: "button" %></span>
        </div>
        <hr align="center" style="width:100%">
        <% end %>
        <p>NEW SYSTEM:</p>
        <span align="left"> <%= button_to "ADD NEW SYSTEM", new_system_path, method: "get", class: "button" %></span>
      </div>

      <div class="col-md-4">
        <h1 align="center">INSPECTIONS</h1>
        <h5><%=@account.last_inspection.inspection_track %></h5>
        <span align="center"> <%= button_to "ADD NEW INSPECTION", new_inspection_path, method: "get", class: "button" %></span><br>
        <%@account.inspections.each do |inspection| %>
        <span align="center">Report Date: <%= link_to "#{inspection.inspection_date}", inspection_path(inspection) %></span><br>
        <% end %>
      </div>

      <div class="col-md-4">
        <h1 align="center">Reports</h1>
        <span align="center"> <%= button_to "ADD NEW REPORT", new_report_path, method: "get", class: "button" %></span><br>
        <%@account.systems.each do |system| %>
          <% system.reports.each do |report|%>
            <span><%= link_to "#{report.system.system_type}, #{report.created_at.strftime("%^B %m %Y")}", report_path(report) %></span><br>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>